                                     WEEK 1

In [ ]:
# Read name, address, email and phone number of a person
# through keyboard and print the details.
name=str(input("enter your name: "))
address=input("enter your address: ")
email=input("give your email id: ")
phone_number=input("enter your phone number: ")
print()

enter your name: Meghana
enter your address: bhudevi hills,kukatpally
give your email id: 23wh1a12c1@bvrithyderabad.edu.in
enter your phone number: 9505113160



In [ ]:
#Write a program to calculate compound interest when principal,
# rate and number of periods are given.
def compound_interest(principal, rate, time):
    Amount = principal * (pow((1 + rate / 100), time))
    CI = Amount - principal
    print("Compound interest is", CI)
compound_interest(80000,2,2)

Compound interest is 3232.0


In [ ]:
#Given coordinates (x1, y1), (x2, y2) find the distance between two points
def distance(x1,y1,x2,y2):
    return( ((x2-x1)**2+(y2-y1)**2)**0.5)
print(distance(1,1,5,4))

5.0


                                                    WEEK 2

In [ ]:
#find Euclidean distance using linalg.norm()
import numpy as np
# initializing points in numpy arrays
point1 = np.array((1, 2, 3))
point2 = np.array((1, 1, 1))
dist = np.linalg.norm(point1 - point2)
print(dist)

2.23606797749979


In [ ]:
# Python code to find Euclidean distance using dot()
import numpy as np
 # initializing points in numpy arrays
point1 = np.array((1, 2, 3))
point2 = np.array((1, 1, 1))
temp = point1 - point2     #subtracting
sum_sq = np.dot(temp.T, temp)     # sum of squares
print(np.sqrt(sum_sq))              # square root of sum

2.23606797749979


In [ ]:
# Python code to find Euclidean distance using sum() and square()

import numpy as np
# initializing points in numpy arrays
point1 = np.array((1, 2, 3))
point2 = np.array((1, 1, 1))

# finding sum of squares
sum_sq = np.sum(np.square(point1 - point2))

# Doing squareroot and printing Euclidean distance
print(np.sqrt(sum_sq))

2.23606797749979


In [ ]:
# importing euclidean distance
# function from scikit-learn library
from sklearn.metrics.pairwise import euclidean_distances
# importing numpy library
import numpy as np
X = np.array([[2.3, 1.6, 7.9],
              [0, 9, 2], [5, 7, 2.9]])
Y = np.array([[34, 2.9, 5.8], [4, 7, 2],
              [6.5, 1, 0]])

distance = euclidean_distances(X, Y)
print(distance)

[[31.79606894  8.17679644  8.96716232]
 [34.75125897  4.47213595 10.5       ]
 [29.43161565  1.3453624   6.83081254]]


In [ ]:
# Find the Euclidean distance with the given values and
# check the validity of values to find the distance.
#Given coordinates (x1, y1), (x2, y2)
def distance(x1,y1,x2,y2):
    return( ((x2-x1)**2+(y2-y1)**2)**0.5)
print(distance(1,1,5,4))

5.0


In [ ]:
# Generate a random number between 1-10 and ask the user to guess the number. Give chance
# for 3 times. If guessed correctly then congratulate otherwise print message as sorry.
def randomNum(count,onum,n):
    if count == 2:
        print("Sorry,you are out of chances")
        return
    if n == onum:
        print("Wow! You guessed it right")
        return
    else:
        print("Sorry! You guessed it wrong.")
        count += 1
        n = guess(n)
        randomNum(count,onum,n)


def guess(n):
    num = int(input("Enter a number from 1-10 "))
    return n

print("Hello! Ready to guess a number?")
ori_num = 6
count = 0
num = int(input("Enter a number from 1-10 "))

for i in range(0,3):
    randomNum(count,ori_num, num)
    break

Hello! Ready to guess a number?
Enter a number from 1-10 4
Sorry! You guessed it wrong.
Enter a number from 1-10 6
Sorry! You guessed it wrong.
Enter a number from 1-10 5
Sorry,you are out of chances


In [ ]:
# Function to swap two characters in a character array
def swap(ch, i, j):
    temp = ch[i]
    ch[i] = ch[j]
    ch[j] = temp


# Recursive function to generate all permutations of a string
def permutations(ch, curr_index=0):

    if curr_index == len(ch) - 1:
        print(''.join(ch))

    for i in range(curr_index, len(ch)):
        swap(ch, curr_index, i)
        permutations(ch, curr_index + 1)
        swap(ch, curr_index, i)

if __name__ == '__main__':


    s = 'ABC'
    permutations(list(s))

ABC
ACB
BAC
BCA
CBA
CAB


In [ ]:
import itertools

if __name__ == '__main__':
    s = 'ABC'

    nums = list(s)
    permutations =list(itertools.permutations(nums))

    # Output: ['ABC', 'ACB', 'BAC', 'BCA', 'CAB', 'CBA']
    print([''.join(permutation) for permutation in permutations])

['ABC', 'ACB', 'BAC', 'BCA', 'CAB', 'CBA']


In [ ]:
# Generate prime numbers of fibonacci series
num = int(input("Enter a number: "))

a = 1
b = 1
c = 0
#count = 0
isPrime = True

while (count < num):
    isPrime = True
    c = a + b

    for i in range(2,c):
        if (c % i == 0):
            isPrime = False
            break

    if (isPrime):
        print (c)
        count = count + 1
    a = b
    b = c

In [ ]:
#Generate prime numbers of fibonacci series between 1-50.
def generate_fibonacci(n):
    fibonacci = [1, 1]
    while True:
        next_fib = fibonacci[-1] + fibonacci[-2]
        if next_fib > n:
            break
        fibonacci.append(next_fib)
    return fibonacci

def is_prime(num):
    if num <= 1:
        return False
    if num == 2:
        return True
    if num % 2 == 0:
        return False
    for i in range(3, int(num**0.5) + 1, 2):
        if num % i == 0:
            return False
    return True

fibonacci_numbers = generate_fibonacci(50)
prime_fibonacci = [num for num in fibonacci_numbers if is_prime(num)]
print("Prime Fibonacci numbers between 1 and 50:", prime_fibonacci)

Prime Fibonacci numbers between 1 and 50: [2, 3, 5, 13]


                            WEEK 3

In [ ]:
# 1. i) Write a program to convert a list and tuple into arrays.
import numpy as np
list=[1,2,3,4]
arr=np.array(list)
print(arr)
tuple=([1,2,3],[4,5,6])                                                    #t=(1,2,3,4)
arr1=np.array(tuple)                                                    #arr=np.array(t)
print(arr1)                                                       #print(arr)              same output

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [ ]:
# ii) Write a program to find common values between two arrays.
import numpy as np
ar1 = [1,2,3,4,5]
ar2 = [2, 4, 5, 6, 7, 8, 9, 12]
# Common values between two arrays
print(np.intersect1d(ar1, ar2))

[2 4 5]


In [ ]:
# Write a program to add comma separators in a given big number as per the standard
# American convention. Ex: i/p: 100000000 o/p: 100,000,000
text=int(input())
print("{:,}".format(text))

100000000
100,000,000


In [ ]:
# Write a program to convert given formula 3X+4Y as 3*X+4*Y and 3(X+Y) as 3*X+3*Y
X=int(input())
Y=int(input())
res=3*X + 4*Y
print("3*{} + 4*{}={}".format(X,Y,res))
res1=3*(X+Y)
print("3*{} + 3*{}={}".format(X,Y,res1))

2
4
3*2 + 4*4=22
3*2 + 3*4=18


In [ ]:
expr=input()   # 3(x+y+z)
result=" "
for symbol in expr:
    if symbol.isnumeric():
        num=symbol
    elif symbol=='('or symbol==')':
        pass
    elif symbol.isalpha():
        result=result+num+'*'+symbol
    else:
        result=result+symbol
print(result)

3x+4y
 3*x+4*y


In [ ]:
# Write a program to convert given formula 3X+4Y as 3*X+4*Y and 3(X+Y) as 3*X+3*Y
# expanding the expression using loops
expr=input()   # 3(x+y+z)
result=" "
for symbol in expr:
    if symbol.isnumeric():
        num=symbol
    elif symbol=='('or symbol==')':
        pass
    elif symbol.isalpha():
        result=result+num+'*'+symbol
    else:
        result=result+symbol
print(result)

3(x+y)
 3*x+3*y


In [ ]:
# Write a program to convert given formula 3X+4Y as 3*X+4*Y and 3(X+Y) as 3*X+3*Y
# expansion of linear eq
from sympy import symbols,expand       # sympy = symbol python
x,y=symbols('x y')
expr=input("enter expression: ")
print(expand(expr))

enter expression: 3*(x+y) - 2*x
x + 3*y


                         WEEK 4
                    

In [ ]:
#1. Write a function called is sorted that takes a list as a parameter and returns True if the list
# issorted in ascending order and False otherwise.
def is_sorted(user_list):
    return user_list == sorted(user_list)
user_list=input("Please enter a list: ")
user_list = user_list.split()
print(is_sorted(user_list))
print("Your list: ", user_list)

Please enter a list: 1 2 3 4 5
True
Your list:  ['1', '2', '3', '4', '5']


In [ ]:
# sorting using numpy by converting list to array
import numpy as np
array = np.array([10, 2, 9, -1])
array2 = np.sort(array)
print(array2)

[-1  2  9 10]


In [ ]:
# 2.Write a function called has duplicates that takes a list and returns True if there is any
# element that appears more than once. It should not modify the original list.
def duplicates(lst):
	checked = []
	for item in lst:
		if item in checked:
			return True
		checked.append(item)
	return False
duplicates([1,4,53,5,3,2,4,2,4,3])

True

In [ ]:
# remove duplicates using set
list1=[1,2,5,5,3,6,3,2,2,4]
def remove_duplicate(list1):
    return list(set(list1))
print(remove_duplicate(list1))

[1, 2, 3, 4, 5, 6]


In [ ]:
#2.i)Write a function called remove duplicates that takes a list and returns a new list with
 # only the unique elements from the original. Hint: they don’t have to be in the same order.
def Remove(duplicate):
    final_list = []
    for num in duplicate:
        if num not in final_list:
            final_list.append(num)
    return final_list

# Driver Code
duplicate = [2, 4, 10, 20, 5, 2, 20, 4]
print(Remove(duplicate))

[2, 4, 10, 20, 5]


In [ ]:
# ii)The wordlist I provided, words.txt, doesn’t contain single letter words. So you might
# want to add “I”, “a”, and the empty string.


In [ ]:
# iii)Write a python code to read dictionary values from the user. Construct a function to
# Invert its content. i.e., keys should be values and values should be keys.
# in dict   keys to values    values to keys
dict1={}
dict2={1:'apple',2:'guava',3:'pineapple'}
new_dict=dict((value,key) for key,value in dict2.items())
print(dict2)
print(new_dict)

{1: 'apple', 2: 'guava', 3: 'pineapple'}
{'apple': 1, 'guava': 2, 'pineapple': 3}


In [ ]:
# iii)Write a python code to read dictionary values from the user. Construct a function to
# Invert its content. i.e., keys should be values and values should be keys.
old_dict = {'A': 67, 'B': 23, 'C': 45, 'D': 56, 'E': 12, 'F': 69, 'G': 67, 'H': 23}
new_dict = dict([(value, key) for key, value in old_dict.items()])
print ("Original dictionary is : ")
print(old_dict)
print()
# Printing new dictionary after swapping keys and values
print ("Dictionary after swapping is :  ")
print("keys: values")
for i in new_dict:
    print(i, " :  ", new_dict[i])

Original dictionary is : 
{'A': 67, 'B': 23, 'C': 45, 'D': 56, 'E': 12, 'F': 69, 'G': 67, 'H': 23}

Dictionary after swapping is :  
keys: values
67  :   G
23  :   H
45  :   C
56  :   D
12  :   E
69  :   F


In [ ]:
# 3. i) Add a comma between the characters. If the given word is 'Apple', it should become
#   'A,p,p,l,e'
txt = 'Apple'
new_txt = ','.join(txt)
print(new_txt)

A,p,p,l,e


In [ ]:
# removing given word from str
txt=input()
word=input()
txt=txt.replace(word,"")
print(txt)

megha is a very bright girl
very
megha is a  bright girl


In [ ]:
# removing given word from str
txt=input()
word=input()
txt=txt.split()
for string in txt:
    if string==word:
        txt.remove(string)
print(" ".join(txt))

megha is a very bright girl
very
megha is a bright girl


In [ ]:
# ii) Remove the given word in all the places in a string?
txt=input("enter str: ")
words=txt.split()
data=input("enter word to delete: ")
for word in words:
    if word==data:
        words.remove(word)
        if status:
            txt=' '.join(words)
print("str after deletion: ",txt)

enter str: meggha dsyd a
enter word to delete: a


NameError: name 'status' is not defined

In [ ]:
# iii) Write a function that takes a sentence as an input parameter and replaces the first letter
# of every word with the corresponding upper-case letter and the rest of the letters in the
# word by corresponding letters in lower case without using a built-in function?
s = "python is learned in 2nd sem of btech in IT-B "
print("Original string:")
print(s)
print("After capitalizing first letter:")
print(s.capitalize())

Original string:
python is learned in 2nd sem of btech in IT-B 
After capitalizing first letter:
Python is learned in 2nd sem of btech in it-b 


In [ ]:
# capitalizing
txt=input()
new_txt=""
for word in txt.split():
    new_txt+=word.capitalize()+""
print(new_txt)

megha
Megha


In [ ]:
# 4. Write a recursive function that generates all binary strings of n-bit length
def binary_str(n,string=''):
    if len(string)== n:
        print(string)
    else:
        binary_str(n,string+"0")
        binary_str(n,string+"1")
n=int(input("length of string: "))
binary_str(n)

length of string: 3
000
001
010
011
100
101
110
111


In [ ]:
# 4. Write a recursive function that generates all binary strings of n-bit length
n = 5
for i in range(2**n, 2**(n+1)):
    print(bin(i)[3:])

00000
00001
00010
00011
00100
00101
00110
00111
01000
01001
01010
01011
01100
01101
01110
01111
10000
10001
10010
10011
10100
10101
10110
10111
11000
11001
11010
11011
11100
11101
11110
11111


In [ ]:
def genbin(n, bs = ''):
    if n-1:
        genbin(n-1, bs + '0')
        genbin(n-1, bs + '1')
    else:
        print('1' + bs)

genbin(4)

1000
1001
1010
1011
1100
1101
1110
1111


In [ ]:
def genbin(n, bs=''):
    if len(bs) == n:
        print(bs)
    else:
        genbin(n, bs + '0')
        genbin(n, bs + '1')
genbin(3)

000
001
010
011
100
101
110
111


                                        WEEK 5

In [ ]:
# 1. i) Write a python program that defines a matrix and prints
R = int(input("Enter the number of rows: "))
C = int(input("Enter the number of columns: "))
matrix = []
print("Enter the elements rowwise one by one: ")
for i in range(R):          # A for loop for row entries
    a =[]
    for j in range(C):      # A for loop for column entries
        a.append(int(input()))
    matrix.append(a)

# For printing the matrix
for i in range(R):
    for j in range(C):
        print(matrix[i][j], end = " ")
    print()

Enter the number of rows: 2
Enter the number of columns: 2
Enter the elements rowwise one by one: 
1
2
3
4
1 2 
3 4 


In [ ]:
# ii) Write a python program to perform addition of two square matrices
# addition of matrix and printing in matrix form
import numpy as np
print("first matrix is: ")
m1=[[1,2,3],
   [1,2,3]]                                       # USING NUMPY
print(m1)
print("second matrix is: ")
m2=[[1,2,3],
   [1,2,3]]
print(m2)
print("sum of matrices is: ")
print(np.add(m1,m2))

first matrix is: 
[[1, 2, 3], [1, 2, 3]]
second matrix is: 
[[1, 2, 3], [1, 2, 3]]
sum of matrices is: 
[[2 4 6]
 [2 4 6]]


In [ ]:
  # ii) Write a python program to perform addition of two square matrices
# matrix addition in python

rows = int(input('ENter number of rows: '))
cols  = int(input('ENter number of column: '))

print() # for new line
                                                      # USING LOOPS

print('Enter values for matrix A')

matrix_A = [[int(input(f"column {j+1} -> ENter {i+1} element:")) for j in range(cols)] for i in range(rows) ]

print() # for new line
print('Enter values for matrix B ')
matrix_B= [[int(input(f"column {j+1} -> ENter {i+1} element:")) for j in range(cols)] for i in range(rows) ]

print() #for new line

print('Matrix-A :')
for i in matrix_A:
    print(i)

print() #for new line

print('Matrix-B :')
for i in matrix_B:
    print(i)

# resultant matrix (matrix that store answer and intially it is Zero)
result = [[0 for j in range(cols)] for i in range(rows)]

# addition
for i in range(rows):
    for j in range(cols):
        result[i][j] = matrix_A[i][j] + matrix_B[i][j]

print() #for new line
print('Addition of Matrix-A and Matrix-B is :')

for i in result:
    print(i)


ENter number of rows: 2
ENter number of column: 2

Enter values for matrix A
column 1 -> ENter 1 element:1
column 2 -> ENter 1 element:2
column 1 -> ENter 2 element:2
column 2 -> ENter 2 element:1

Enter values for matrix B 
column 1 -> ENter 1 element:1
column 2 -> ENter 1 element:2
column 1 -> ENter 2 element:2
column 2 -> ENter 2 element:1

Matrix-A :
[1, 2]
[2, 1]

Matrix-B :
[1, 2]
[2, 1]

Addition of Matrix-A and Matrix-B is :
[2, 4]
[4, 2]


In [ ]:
# 1.iii) Write a python program to perform multiplication of two square matrices
# Program to multiply two matrices using nested loops
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
Y = [[5,8,1],                                    # USING LOOPS
    [6,7,3],
    [4,5,9]]
result = [[0,0,0],
          [0,0,0],
          [0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)


[114, 160, 60]
[74, 97, 73]
[119, 157, 112]


In [ ]:
# 1.iii) Write a python program to perform multiplication of two square matrices
# Program to multiply two matrices using nested loops by taki8ng input from user
# multiplication of matrix and printing in matrix form
import numpy as np
print("first matrix is: ")
m1=[[1,2,3],
   [1,2,3]]                                                        #USING  NUMPY
print(m1)
print("second matrix is: ")
m2=[[1,2,3],
   [4,5,6]]
print(m2)
print("multiplication of matrices is: ")
print(np.multiply(m1,m2))

In [ ]:
# matrix multiplication in python
matrix_A_rows = int(input('ENter number of rows for matrix-A: '))
matrix_A_cols  = int(input('ENter number of columns for matrix-A: '))

print() # for new line

matrix_B_rows = int(input('ENter number of rows for matrix-B: '))
matrix_B_cols  = int(input('ENter number of columns for matrix-B: '))

print() # for new line

if matrix_A_cols == matrix_B_rows:
    print('Enter values for matrix A')
    matrix_A = [[int(input(f"column {j+1} -> ENter {i+1} element:")) for j in range(matrix_A_cols)] for i in range(matrix_A_rows) ]

    print() # for new line

    print('Enter values for matrix B ')
    matrix_B = [[int(input(f"column {j+1} -> ENter {i+1} element:")) for j in range(matrix_B_cols)] for i in range(matrix_B_rows) ]

    print() #for new line

    print('Matrix-A :')
    for i in matrix_A:
        print(i)

    print() #for new line

    print('Matrix-B :')
    for i in matrix_B:
        print(i)

    # mutiplication operation

    # resultant matrix (matrix that store answer and intially it is Zero)
    result = [[0 for j in range(matrix_B_cols)] for i in range(matrix_A_rows)]

    # main logic for matrix multiplication (multiplication operation)
    for i in range(len(matrix_A)):
        for j in range(len(matrix_B[0])):
            for k in range(len(matrix_B)):
                result[i][j] += matrix_A[i][k] * matrix_B[k][j]

    print() #for new line

    print('Multiplication of Matrix-A and Matrix-B is :')
    for i in result:  #print result
        print(i)

else:
    print('Multiplication of matrices is not possible (columns of matrix-A = row of matrix-B)')


ENter number of rows for matrix-A: 2
ENter number of columns for matrix-A: 2

ENter number of rows for matrix-B: 2
ENter number of columns for matrix-B: 2

Enter values for matrix A
column 1 -> ENter 1 element:1
column 2 -> ENter 1 element:2
column 1 -> ENter 2 element:2
column 2 -> ENter 2 element:1

Enter values for matrix B 
column 1 -> ENter 1 element:2
column 2 -> ENter 1 element:1
column 1 -> ENter 2 element:2
column 2 -> ENter 2 element:1

Matrix-A :
[1, 2]
[2, 1]

Matrix-B :
[2, 1]
[2, 1]

Multiplication of Matrix-A and Matrix-B is :
[6, 3]
[6, 3]


In [ ]:
  #  2. How do you make a module? Give an example of construction of a module using
#  different geometrical shapes and operations on them as its functions.
# Python program to create
# a module

# Defining a function
''' GFG.py '''
def Geeks():
    print("GeeksforGeeks")

# Defining a variable
location = "Noida"
import GFG

# Use the function created
GFG.Geeks()

# Print the variable declared
print(GFG.location)

ModuleNotFoundError: No module named 'GFG'

In [ ]:
# 3.Use the structure of exception handling all general purpose exceptions.

                     # using syntax error

amount = 10000
if(amount > 2999):
    print("You are eligible to purchase ")


You are eligible to purchase Dsa Self Paced


In [1]:
#
try:
    numerator = 10
    denominator = 0

    result = numerator/denominator

    print(result)
except:
    print("Error: Denominator cannot be 0.")

# Output: Error: Denominator cannot be 0.

Error: Denominator cannot be 0.
